const ADDTOCART = 'ADD_TO_CART'
const UPDATETOCART = 'UPDATE_TO_CART'
const DELETETOCART = 'DELETE_TO_CART'
const SETPRODUCTS = 'SET_PRODUCTS'

export default {ADDTOCART,UPDATETOCART, DELETETOCART, SETPRODUCTS};

